
variable "description" {
  type    = string
  default = "webserver"
}

variable "version" {
  type    = string
  default = "1.0"
}

source "amazon-ebs" "autogenerated_1" {
  access_key    = "${{ secrets.AWS_ACCESS_KEY }}"
  ami_name      = "${var.description}-${var.version}"
  instance_type = "t2.micro"
  region        = "us-east-1"
  secret_key    = "${{ secrets.AWS_SECRET_KEY }}"
  source_ami    = "ami-0cff7528ff583bf9a"
  ssh_username  = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

}
